name: experiment                        # name of the config. DOES NOT HAVE SPACE ON IT


# model options
model:
    loss: MaskedMSELoss                 # Loss function
    learning_rate: 0.001                # learning rate
    embedding_dim: 64                   # dimension of embedding
    hidden_layer_1: 32                  # output dimention of the first hidden layer
    hidden_layer_2: 2                   # output dimention of the second hidden layer
    dropout: 0                          # dropouy probability
    save_checkpoint: best               # if you want save the models weight: all, last, best or false


# data options
data:
    path: data\Dataset.csv              # data path
    nb_users: 944
    nb_items: 1682
    split_1: 0.6
    split_2: 0.2

metrics:
    truc: false

# train options
train:
    epochs: 50                          # number of epochs
    save_learning_curves: true          # save the learning curves
    logs_path: logs                     # path to logs folder

